export const profilePermission = [
	{
		id: '1',
		name: 'Acueducto',
		action: '',
		icon: '',
		level: '0',
		group_menu: '1',
		sub_menu: null,
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '2',
		name: 'Administraci\u00f3n',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: '',
	},
	{
		id: '40',
		name: 'Inmuebles - Contribuyentes',
		action: 'acueduct_texpayers()',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: '',
	},
	{
		id: '51',
		name: 'Facturaci\u00f3n',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: '',
	},
	{
		id: '64',
		name: 'Tesoreria y Cajas',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '74',
		name: 'Gesti\u00f3n de Deuda',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: '',
	},
	{
		id: '45',
		name: 'Conceptos',
		action: 'concepts_aqueduct()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: '',
	},
	{
		id: '46',
		name: 'Tipos de Comprobantes',
		action: 'acueduct_Type_voucher_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: '',
	},
	{
		id: '47',
		name: 'Referencias',
		action: 'aqueduct_references()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: '',
	},
	{
		id: '48',
		name: 'Par\u00e1metros',
		action: 'aqueduct_parameter_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: '',
	},
	{
		id: '49',
		name: 'Tipos Planes de Pago',
		action: 'payment_plans_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: '',
	},
	{
		id: '50',
		name: 'Importar Calles',
		action: 'acueduct_importTXT()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: '',
	},
	{
		id: '52',
		name: 'Facturaci\u00f3n manual',
		action: 'viewInvoicesIndividual()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: '',
	},
	{
		id: '54',
		name: 'Cambio d/Precios Masivo',
		action: 'aqueduct_update_dues()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: '',
	},
	{
		id: '55',
		name: 'Prefacturaci\u00f3n',
		action: 'pre_invoicing()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: '',
	},
	{
		id: '57',
		name: 'Facturaci\u00f3n Masiva',
		action: 'invoicing()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: '',
	},
	{
		id: '58',
		name: 'Control Facturaci\u00f3n',
		action: 'filter_invoice()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: '',
	},
	{
		id: '59',
		name: 'Informes',
		action: '',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: '',
	},
	{
		id: '65',
		name: 'Consulta de Cajas',
		action: 'aqueduct_list_box()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '66',
		name: 'Cobranza Local',
		action: 'box_collection()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '67',
		name: 'Operaciones de Caja',
		action: 'operation_box()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '69',
		name: 'Planilla s/Recibo',
		action: 'recipes_list()',
		icon: 'fas fa-receipt',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '70',
		name: 'Importar Cobranza',
		action: 'import_pay_ext()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: '',
	},
	{
		id: '71',
		name: 'Consulta Cobranzas Ext.',
		action: 'collection_consultation()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: '',
	},
	{
		id: '72',
		name: 'Cheques Recibidos',
		action: 'aqueduct_check_received()',
		icon: 'fas fa-money-check',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: '',
	},
	{
		id: '73',
		name: 'Tarjetas Recibidas',
		action: 'aqueduct_cards_received()',
		icon: 'fas fa-credit-card',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: '',
	},
	{
		id: '75',
		name: 'Emitir Plan de Pago',
		action: 'payment_plans()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
		checked: '',
	},
	{
		id: '76',
		name: 'Consulta Plan de Pago',
		action: 'pyment_consult_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
		checked: '',
	},
	{
		id: '77',
		name: 'Desbloquear Cedulones',
		action: 'aqueduct_blocked()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
		checked: '',
	},
	{
		id: '82',
		name: 'Importar Inmuebles',
		action: 'import_txt_muni()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: '',
	},
	{
		id: '87',
		name: 'Totales Cobrados',
		action: 'acueduct_total_cobros()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: '',
	},
	{
		id: '91',
		name: 'Generar Cuotas',
		action: 'aqueduct_importFee()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: '',
	},
	{
		id: '92',
		name: 'Usuarios Vinculados',
		action: 'users_accounts_aqueduct()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: '',
	},
	{
		id: '93',
		name: 'Exportar Cedulones',
		action: 'aqueduct_exportPayments()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: '',
	},
	{
		id: '60',
		name: 'Cuotas No Facturadas',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
		checked: '',
	},
	{
		id: '61',
		name: 'Notas de Cr\u00e9ditos',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
		checked: 'checked',
	},
	{
		id: '62',
		name: 'Cuentas No Facturar',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
		checked: '',
	},
	{
		id: '63',
		name: 'Comp. Bloqueados',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
		checked: '',
	},
	{
		id: '80',
		name: 'Desarrollo',
		action: '',
		icon: 'fa fa-file',
		level: '0',
		group_menu: '2',
		sub_menu: null,
		status: '1',
		checked: '',
	},
	{
		id: '81',
		name: 'Migraci\u00f3n Acueducto',
		action: 'prueba_jose2()',
		icon: '',
		level: '1',
		group_menu: '2',
		sub_menu: '80',
		status: '1',
		checked: '',
	},
	{
		id: '83',
		name: 'Coopate',
		action: '',
		icon: 'fas fa-dumpster',
		level: '0',
		group_menu: '3',
		sub_menu: null,
		status: '1',
		checked: '',
	},
	{
		id: '84',
		name: 'Beneficios CoopMorteros',
		action: 'grafico_canjes_coop()',
		icon: '',
		level: '1',
		group_menu: '3',
		sub_menu: '83',
		status: '1',
		checked: '',
	},
	{
		id: '85',
		name: 'Graficos Externos',
		action: 'grafico_canjes_x_socio()',
		icon: '',
		level: '1',
		group_menu: '3',
		sub_menu: '83',
		status: '1',
		checked: '',
	},
]
export const profilePermission2 = [
	{
		id: '1',
		name: 'Mapa',
		path: '/map',
		action: '',
		icon: '',
		level: '0',
		group_menu: '1',
		sub_menu: null,
		status: '1',
	},
	{
		id: 2,
		name: 'Alertas',
		path: '/Alert',
		action: '',
		icon: '',
		level: '0',
		group_menu: '2',
		sub_menu: null,
		status: '1',
	},
	{
		id: 3,
		name: 'Diagrama',
		path: '/Diagram',
		action: '',
		icon: '',
		level: '0',
		group_menu: '3',
		sub_menu: null,
		status: '1',
	},
	{
		id: 4,
		path: '/tabs',
		status: '1',
		name: 'Pestañas',
		group_menu: '4',
		action: '',
		icon: '',
		level: '0',
		sub_menu: null,
	},
	{
		id: 5,
		path: '/config',
		status: 1,
		name: 'Configuracion',
		group_menu: '5',
		action: '',
		icon: '',
		level: '0',
		sub_menu: null,
	},
	{
		id: 6,
		path: '/config/security',
		status: 1,
		name: 'Configuracion Seguridad',
		group_menu: '5',
		action: '',
		icon: '',
		level: '1',
		sub_menu: 5,
	},
	{
		id: 7,
		path: '/config/menu',
		status: 0,
		name: 'Configuracion Menu',
		group_menu: '5',
		action: '',
		icon: '',
		level: '1',
		sub_menu: 5,
	},
	{
		id: 8,
		path: '/notificaciones',
		status: 1,
		name: 'Notificaciones',
		group_menu: '6',
		action: '',
		icon: '',
		level: '0',
		sub_menu: null,
	},
	{
		id: 9,
		path: '/board/:id',
		status: 1,
		name: 'Tableros',
		group_menu: '7',
		action: '',
		icon: '',
		level: '0',
		sub_menu: null,
	},
	{
		id: 10,
		path: '/Abm/:name',
		status: 1,
		name: 'Altas',
		group_menu: '8',
		action: '',
		icon: '',
		level: '0',
		sub_menu: null,
	},
	{
		id: 11,
		path: '/Abm/:name/:id',
		status: 1,
		name: 'Edicion',
		group_menu: '9',
		action: '',
		icon: '',
		level: '0',
		sub_menu: null,
	},
	{
		id: 12,
		path: '/profile',
		status: 1,
		name: 'Perfil',
		group_menu: '10',
		action: '',
		icon: '',
		level: '0',
		sub_menu: null,
	},
]

export const userPermission = [
	{
		id: '1',
		name: 'Acueducto',
		action: '',
		icon: '',
		level: '0',
		group_menu: '1',
		sub_menu: null,
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '2',
		name: 'Administraci\u00f3n',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '40',
		name: 'Inmuebles - Contribuyentes',
		action: 'acueduct_texpayers()',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '51',
		name: 'Facturaci\u00f3n',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '64',
		name: 'Tesoreria y Cajas',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '74',
		name: 'Gesti\u00f3n de Deuda',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '45',
		name: 'Conceptos',
		action: 'concepts_aqueduct()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '46',
		name: 'Tipos de Comprobantes',
		action: 'acueduct_Type_voucher_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '47',
		name: 'Referencias',
		action: 'aqueduct_references()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '48',
		name: 'Par\u00e1metros',
		action: 'aqueduct_parameter_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '49',
		name: 'Tipos Planes de Pago',
		action: 'payment_plans_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '50',
		name: 'Importar Calles',
		action: 'acueduct_importTXT()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '52',
		name: 'Facturaci\u00f3n manual',
		action: 'viewInvoicesIndividual()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '54',
		name: 'Cambio d/Precios Masivo',
		action: 'aqueduct_update_dues()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '55',
		name: 'Prefacturaci\u00f3n',
		action: 'pre_invoicing()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '57',
		name: 'Facturaci\u00f3n Masiva',
		action: 'invoicing()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '58',
		name: 'Control Facturaci\u00f3n',
		action: 'filter_invoice()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '59',
		name: 'Informes',
		action: '',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '65',
		name: 'Consulta de Cajas',
		action: 'aqueduct_list_box()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '66',
		name: 'Cobranza Local',
		action: 'box_collection()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '67',
		name: 'Operaciones de Caja',
		action: 'operation_box()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '69',
		name: 'Planilla s/Recibo',
		action: 'recipes_list()',
		icon: 'fas fa-receipt',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '70',
		name: 'Importar Cobranza',
		action: 'import_pay_ext()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '71',
		name: 'Consulta Cobranzas Ext.',
		action: 'collection_consultation()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '72',
		name: 'Cheques Recibidos',
		action: 'aqueduct_check_received()',
		icon: 'fas fa-money-check',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '73',
		name: 'Tarjetas Recibidas',
		action: 'aqueduct_cards_received()',
		icon: 'fas fa-credit-card',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '75',
		name: 'Emitir Plan de Pago',
		action: 'payment_plans()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '76',
		name: 'Consulta Plan de Pago',
		action: 'pyment_consult_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '77',
		name: 'Desbloquear Cedulones',
		action: 'aqueduct_blocked()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '82',
		name: 'Importar Inmuebles',
		action: 'import_txt_muni()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '87',
		name: 'Totales Cobrados',
		action: 'acueduct_total_cobros()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '91',
		name: 'Generar Cuotas',
		action: 'aqueduct_importFee()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '92',
		name: 'Usuarios Vinculados',
		action: 'users_accounts_aqueduct()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '93',
		name: 'Exportar Cedulones',
		action: 'aqueduct_exportPayments()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '60',
		name: 'Cuotas No Facturadas',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '61',
		name: 'Notas de Cr\u00e9ditos',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '62',
		name: 'Cuentas No Facturar',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '63',
		name: 'Comp. Bloqueados',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
		checked: 'checked',
		disabled: 'disabled',
	},
	{
		id: '80',
		name: 'Desarrollo',
		action: '',
		icon: 'fa fa-file',
		level: '0',
		group_menu: '2',
		sub_menu: null,
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '81',
		name: 'Migraci\u00f3n Acueducto',
		action: 'prueba_jose2()',
		icon: '',
		level: '1',
		group_menu: '2',
		sub_menu: '80',
		status: '1',
		checked: 'checked',
		disabled: '',
	},
	{
		id: '83',
		name: 'Coopate',
		action: '',
		icon: 'fas fa-dumpster',
		level: '0',
		group_menu: '3',
		sub_menu: null,
		status: '1',
		checked: '',
	},
	{
		id: '84',
		name: 'Beneficios CoopMorteros',
		action: 'grafico_canjes_coop()',
		icon: '',
		level: '1',
		group_menu: '3',
		sub_menu: '83',
		status: '1',
		checked: '',
	},
	{
		id: '85',
		name: 'Graficos Externos',
		action: 'grafico_canjes_x_socio()',
		icon: '',
		level: '1',
		group_menu: '3',
		sub_menu: '83',
		status: '1',
		checked: '',
	},
]
