export const dataElectricity = {
	Objetos: [
		{
			id: 1,
			key: '19',
			left: 437,
			top: 450,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'aperturaCFlecha.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'llave 2',
			caption: '',
			imgsrc: ' ',
		},
		{
			id: 2,
			key: '20',
			left: 260,
			top: 450,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'aperturaCFlecha.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'llave 2',
			caption: '',
			imgsrc: ' ',
		},
		{
			id: 3,
			key: '21',
			left: 1205,
			top: 280,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'aperturaCFlecha.png',
			color_object: 'yellow',
			text_aling: 'rigth',
			text: 'TI:',
			description: 'Distr 4',
			caption: '',
			imgsrc: ' ',
		},
		{
			id: 4,
			key: '22',
			left: 1005,
			top: 280,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'aperturaCFlecha.png',
			color_object: 'yellow',
			text_aling: 'rigth',
			text: 'TI:',
			description: 'Distr 3',
			caption: '',
			imgsrc: ' ',
		},
		{
			id: 5,
			key: '23',
			left: 805,
			top: 280,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'aperturaCFlecha.png',
			color_object: 'yellow',
			text_aling: 'rigth',
			text: 'TI:',
			description: 'Distr 2',
			caption: '',
			imgsrc: ' ',
		},
		{
			id: 6,
			key: '24',
			left: 606,
			top: 280,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'aperturaCFlecha.png',
			color_object: 'yellow',
			text_aling: 'rigth',
			text: 'TI:',
			description: 'Distr 1',
			caption: '',
			imgsrc: ' ',
		},
		{
			id: 7,
			key: '25',
			left: 358,
			top: 280,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'aperturaCFlecha.png',
			color_object: 'yellow',
			text_aling: 'rigth',
			text: 'TI:',
			description: 'llave 2',
			caption: '',
			imgsrc: ' ',
		},
		{
			id: 8,
			key: '26',
			left: 120,
			top: 280,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'aperturaCFlecha.png',
			color_object: 'yellow',
			text_aling: 'rigth',
			text: 'TI:',
			description: 'llave 1',
			caption: '',
			imgsrc: ' ',
		},
		{
			id: 9,
			key: '1',
			left: 774,
			top: 22,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'dobleCirculoFlecha.png',
			color_object: 'yellow',
			text_aling: 'rigth',
			text: '  Trafo 2 \n 25 MVA',
			description: 'Trafo',
			caption: ' ',
			imgsrc: ' ',
		},
		{
			id: 10,
			key: '2',
			left: 495,
			top: 22,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'dobleCirculoFlecha.png',
			color_object: 'yellow',
			text_aling: 'left',
			text: ' Trafo 1 \n 25 MVA',
			description: 'Trafo',
			caption: ' ',
			imgsrc: ' ',
		},
		{
			id: 11,
			key: '27',
			left: 261,
			top: 583,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'FlechaAbajo.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'D2O',
			caption: 'Alim 2',
			imgsrc: ' ',
		},
		{
			id: 12,
			key: '28',
			left: 121,
			top: 387,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'FlechaAbajo.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'D1O',
			caption: 'Alim 1',
			imgsrc: ' ',
		},
		{
			id: 13,
			key: '29',
			left: 608,
			top: 387,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'FlechaAbajo.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'D1E',
			caption: 'Distr 1',
			imgsrc: ' ',
		},
		{
			id: 14,
			key: '30',
			left: 807,
			top: 387,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'FlechaAbajo.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'D2E',
			caption: 'Distr 2',
			imgsrc: ' ',
		},
		{
			id: 15,
			key: '31',
			left: 1008,
			top: 387,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'FlechaAbajo.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'D3E',
			caption: 'Distr 3',
			imgsrc: ' ',
		},
		{
			id: 16,
			key: '32',
			left: 1207,
			top: 387,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'FlechaAbajo.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'D4E',
			caption: 'Distr 4',
			imgsrc: ' ',
		},
		{
			id: 17,
			key: '33',
			left: 440,
			top: 583,
			width: 80,
			heigth: 80,
			type: 'img',
			pic: 'FlechaAbajo.png',
			color_object: 'yellow',
			text_aling: '',
			text: '',
			description: 'D3O',
			caption: 'Alim 2',
			imgsrc: ' ',
		},
	],
	Lineas: [
		{
			id: 56,
			key: 'linea_2',
			type: 'line',
			key_objet: 25,
			points: [398, 442, 300, 442, 300, 460],
			text: 'union 1 alimentador 2 este',
		},
		{
			id: 57,
			key: 'linea_1',
			type: 'line',
			key_objet: 2,
			points: [534, 85, 534, 155, 679, 155],
			text: 'union transfo 1',
		},
		{ id: 58, key: 'linea_2', type: 'line', key_objet: -1, points: [108, 256, 1288, 256], text: 'Barra' },
		{
			id: 60,
			key: 'linea_2',
			type: 'line',
			key_objet: -1,
			points: [159, 257, 159, 290],
			text: 'linea 1 alimentador 1 este',
		},
		{
			id: 61,
			key: 'linea_2',
			type: 'line',
			key_objet: 26,
			points: [159, 352, 159, 405],
			text: 'linea 2 alimentador 1 este',
		},
		{
			id: 64,
			key: 'linea_2',
			type: 'line',
			key_objet: 1,
			points: [815, 85, 815, 155, 679, 155],
			text: 'union trafo 2',
		},
		{ id: 68, key: 'linea_2', type: 'line', key_objet: -1, points: [397, 254, 397, 290], text: 'linea 1 alimen 2' },
		{ id: 70, key: 'linea_2', type: 'line', key_objet: 25, points: [397, 350, 397, 439], text: 'linea 3 alimen 2' },
		{ id: 71, key: 'linea_2', type: 'line', key_objet: 20, points: [299, 522, 299, 600], text: 'linea 1 D20' },
		{ id: 73, key: 'linea_2', type: 'line', key_objet: 19, points: [477, 522, 477, 600], text: 'linea 1 D30' },
		{
			id: 75,
			key: 'linea_2',
			type: 'line',
			key_objet: -1,
			points: [645, 255, 645, 290],
			text: 'linea 1 distr 1 este',
		},
		{
			id: 76,
			key: 'linea_2',
			type: 'line',
			key_objet: 24,
			points: [645, 352, 645, 405],
			text: 'linea 2 distr 1 este',
		},
		{
			id: 77,
			key: 'linea_2',
			type: 'line',
			key_objet: -1,
			points: [845, 257, 845, 290],
			text: 'linea 1 distr 2 este',
		},
		{
			id: 78,
			key: 'linea_2',
			type: 'line',
			key_objet: 23,
			points: [845, 352, 845, 405],
			text: 'linea 2 distr 2 este',
		},
		{
			id: 79,
			key: 'linea_2',
			type: 'line',
			key_objet: -1,
			points: [1045, 257, 1045, 290],
			text: 'linea 1 distr 3 este',
		},
		{
			id: 80,
			key: 'linea_2',
			type: 'line',
			key_objet: 22,
			points: [1045, 352, 1045, 405],
			text: 'linea 2 distr 3 este',
		},
		{
			id: 81,
			key: 'linea_2',
			type: 'line',
			key_objet: -1,
			points: [1245, 257, 1245, 290],
			text: 'linea 1 distr 4 este',
		},
		{
			id: 82,
			key: 'linea_2',
			type: 'line',
			key_objet: 21,
			points: [1245, 352, 1245, 405],
			text: 'linea 2 distr 4 este',
		},
		{
			id: 83,
			key: 'linea_2',
			type: 'line',
			key_objet: 25,
			points: [398, 442, 477, 442, 477, 460],
			text: 'union 2 alimentador 2 este',
		},
		{
			id: 84,
			key: 'linea_2',
			type: 'line',
			key_objet: -1,
			points: [677, 156, 677, 255],
			text: 'union trafos con barra',
		},
		{ id: 85, key: 'linea_2', type: 'line', key_objet: 2, points: [535, 0, 535, 39], text: 'trafo 1 entrada' },
		{ id: 86, key: 'linea_2', type: 'line', key_objet: 1, points: [814, 0, 814, 39], text: 'trafo 2 entrada' },
	],
}
