// Datos ficticios para desarrollo sin backend.
// Replican la estructura que devolverán los endpoints reales.

export const mockEquipos = [
	{ id: 'MED01', nombre: 'SETA 64 — RP1', tipo: 'medidor', tipoLabel: 'Medidor', ubicacion: 'RP1' },
	{ id: 'MED02', nombre: 'Cliente Industrial Sur', tipo: 'medidor', tipoLabel: 'Medidor', ubicacion: 'Av. San Martín 1240' },
	{ id: 'ANA03', nombre: 'POWERMETER 03', tipo: 'analizador', tipoLabel: 'Analizador de red', ubicacion: 'SE Norte' },
	{ id: 'GEN01', nombre: 'Generador Sala 2', tipo: 'generador', tipoLabel: 'Generador diésel', ubicacion: 'Edificio central' },
	{ id: 'RE02', nombre: 'Diego de Rojas', tipo: 'reconectador', tipoLabel: 'Reconectador', ubicacion: 'Línea rural 04' },
	{ id: 'RE07', nombre: 'Camino Viejo', tipo: 'reconectador', tipoLabel: 'Reconectador', ubicacion: 'Acceso oeste' },
	{ id: 'SEU04', nombre: 'El Centro', tipo: 'subestacion', tipoLabel: 'Subestación urbana', ubicacion: 'Bv. 25 de Mayo' },
	{ id: 'SER12', nombre: 'BE1 — Brinkmann', tipo: 'subestacion', tipoLabel: 'Subestación rural', ubicacion: 'Camino vecinal 8' },
	{ id: 'TR145', nombre: 'TR-145 · 25 kVA', tipo: 'transformador', tipoLabel: 'Transformador', ubicacion: 'Esq. Mitre y Belgrano' },
	{ id: 'TR208', nombre: 'TR-208 · 100 kVA', tipo: 'transformador', tipoLabel: 'Transformador', ubicacion: 'Industrial este' },
]

export const mockPersonal = [
	{ id: 'JP', nombre: 'Juan Pérez', rol: 'Operador' },
	{ id: 'MG', nombre: 'María González', rol: 'Técnica' },
	{ id: 'CR', nombre: 'Carlos Ruiz', rol: 'Operador' },
	{ id: 'SM', nombre: 'Sergio Méndez', rol: 'Técnico' },
	{ id: 'AT', nombre: 'Andrés Torres', rol: 'Operador' },
]

export const mockVehiculos = [
	{ id: 'V04', patente: 'AB123CD', descripcion: 'Camioneta 04', tipo: 'camioneta' },
	{ id: 'V11', patente: 'AE456FG', descripcion: 'Camioneta 11', tipo: 'camioneta' },
	{ id: 'V02', patente: 'AC789HI', descripcion: 'Grúa 02', tipo: 'grua' },
	{ id: 'V07', patente: 'AD012JK', descripcion: 'Hidroelevador', tipo: 'hidroelevador' },
]

export const mockOrdenes = [
	{
		id: 'BIT-2026-0142',
		numeroOM: 'OM-124891',
		equipoId: 'SER12',
		tipoTarea: 'cambio',
		tipoTareaLabel: 'Cambio de equipo',
		descripcion: 'Cambio de transformador de 16 a 25 kVA. Se desconectó la línea, se retiró el equipo viejo y se montó el nuevo. Pruebas de aislación OK.',
		fechaRealizacion: '2026-05-16',
		duracion: { dias: 0, horas: 5, minutos: 30 },
		personalIds: ['JP', 'MG', 'CR'],
		vehiculosIds: ['V04', 'V02'],
		estado: 'curso',
		fotoGeneral: null,
		fotosDetalle: [],
	},
	{
		id: 'BIT-2026-0141',
		numeroOM: 'OM-124855',
		equipoId: 'MED02',
		tipoTarea: 'preventivo',
		tipoTareaLabel: 'Mant. preventivo',
		descripcion: 'Limpieza y verificación de bornes de conexión. Se ajustaron tornillos a 12 Nm. Sin observaciones.',
		fechaRealizacion: '2026-05-14',
		duracion: { dias: 0, horas: 2, minutos: 30 },
		personalIds: ['JP', 'MG'],
		vehiculosIds: ['V04'],
		estado: 'completada',
		fotoGeneral: null,
		fotosDetalle: [],
	},
	{
		id: 'BIT-2026-0140',
		numeroOM: '',
		equipoId: 'GEN01',
		tipoTarea: 'inspeccion',
		tipoTareaLabel: 'Inspección',
		descripcion: 'Inspección mensual y prueba de arranque. Niveles OK. Próximo servicio: cambio de aceite en 30 días.',
		fechaRealizacion: '2026-05-12',
		duracion: { dias: 0, horas: 1, minutos: 15 },
		personalIds: ['SM'],
		vehiculosIds: [],
		estado: 'completada',
		fotoGeneral: null,
		fotosDetalle: [],
	},
	{
		id: 'BIT-2026-0139',
		numeroOM: 'OM-124802',
		equipoId: 'MED01',
		tipoTarea: 'correctivo',
		tipoTareaLabel: 'Mant. correctivo',
		descripcion: 'Reemplazo de display dañado. Calibración post-instalación verificada.',
		fechaRealizacion: '2026-05-10',
		duracion: { dias: 0, horas: 3, minutos: 0 },
		personalIds: ['CR', 'AT'],
		vehiculosIds: ['V11'],
		estado: 'completada',
		fotoGeneral: null,
		fotosDetalle: [],
	},
	{
		id: 'BIT-2026-0138',
		numeroOM: 'OM-124790',
		equipoId: 'SEU04',
		tipoTarea: 'correctivo',
		tipoTareaLabel: 'Mant. correctivo',
		descripcion: 'Reemplazo de seccionador F3 por desgaste. Falla detectada en alarma.',
		fechaRealizacion: '2026-05-08',
		duracion: { dias: 0, horas: 4, minutos: 0 },
		personalIds: ['JP', 'MG', 'SM', 'AT'],
		vehiculosIds: ['V04', 'V07'],
		estado: 'completada',
		fotoGeneral: null,
		fotosDetalle: [],
	},
	{
		id: 'BIT-2026-0137',
		numeroOM: '',
		equipoId: 'TR145',
		tipoTarea: 'inspeccion',
		tipoTareaLabel: 'Inspección',
		descripcion: 'Termografía y medición PAT. Temperatura dentro de rango. PAT: 8 Ω.',
		fechaRealizacion: '2026-05-06',
		duracion: { dias: 0, horas: 1, minutos: 0 },
		personalIds: ['MG'],
		vehiculosIds: [],
		estado: 'completada',
		fotoGeneral: null,
		fotosDetalle: [],
	},
	{
		id: 'BIT-2026-0136',
		numeroOM: 'OM-124771',
		equipoId: 'ANA03',
		tipoTarea: 'instalacion',
		tipoTareaLabel: 'Instalación',
		descripcion: 'Puesta en servicio de analizador y configuración de relaciones de transformación. Tx Reconecta sincronizado.',
		fechaRealizacion: '2026-05-22',
		duracion: { dias: 0, horas: 6, minutos: 0 },
		personalIds: ['SM', 'CR'],
		vehiculosIds: ['V11'],
		estado: 'programada',
		fotoGeneral: null,
		fotosDetalle: [],
	},
	{
		id: 'BIT-2026-0135',
		numeroOM: 'OM-124712',
		equipoId: 'RE07',
		tipoTarea: 'correctivo',
		tipoTareaLabel: 'Mant. correctivo',
		descripcion: 'Falla intermitente en comando de cierre. Pendiente repuesto.',
		fechaRealizacion: '2026-04-28',
		duracion: { dias: 0, horas: 0, minutos: 0 },
		personalIds: ['JP'],
		vehiculosIds: [],
		estado: 'vencida',
		fotoGeneral: null,
		fotosDetalle: [],
	},
]

export const mockStats = {
	totalMes: 142,
	enCurso: 7,
	completadasMes: 28,
	variacionCompletadas: '+12 %',
	vencidas: 2,
	conteosPorEstado: {
		all: 142,
		curso: 7,
		programada: 15,
		completada: 118,
		vencida: 2,
		cancelada: 0,
	},
}
