export const dataGraficos = [
	{
		title: 'Tensiones (V)',
		names: ['Tensión L1', 'Tensión L2', 'Tensión L3'],
		keys: ['V_0', 'V_1', 'V_2'],
		disable: false,
		config: '',
	},
	{
		title: 'Corrientes (A)',
		names: ['Corriente L1', 'Corriente L2', 'Corriente L3'],
		keys: ['I_0', 'I_1', 'I_2'],
		disable: false,
		config: '',
	},
	{
		title: 'Potencias Activas Importada (kW)',
		names: ['Activa Imp. L1', 'Activa Imp. L2', 'Activa Imp. L3'],
		keys: ['IAcP_0', 'IAcP_1', 'IAcP_2'],
		disable: false,
		select: true,
		config: '',
	},
	{
		title: 'Potencias Activas Exportada (kW)',
		names: ['Activa Exp. L1', 'Activa Exp. L2', 'Activa Exp. L3'],
		keys: ['EAcP_0', 'EAcP_1', 'EAcP_2'],
		select: true,
		disable: true,
		config: '',
	},
	{
		title: 'Potencias Aparentes Importada (kVA)',
		names: ['Aparente Imp. L1', 'Aparente Imp. L2', 'Aparente Imp. L3'],
		keys: ['IApP_0', 'IApP_1', 'IApP_2'],
		disable: false,
		config: '',
	},
	{
		title: 'Potencias Aparentes Exportada (kVA)',
		names: ['Aparente Exp. L1', 'Aparente Exp. L2', 'Aparente Exp. L3'],
		keys: ['EApP_0', 'EApP_1', 'EApP_2'],
		disable: true,
		config: '',
	},
	{
		title: 'Potencias Reactivas Importada (kVAr)',
		names: ['Reactiva imp. L1', 'Reactiva imp. L2', 'Reactiva imp. L3'],
		keys: ['IReP_0', 'IReP_1', 'IReP_2'],
		disable: false,
		config: '',
	},
	{
		title: 'Potencias Reactivas Exportada (kVAr)',
		names: ['Reactiva exp. L1', 'Reactiva exp. L2', 'Reactiva exp. L3'],
		keys: ['EReP_0', 'EReP_1', 'EReP_2'],
		disable: true,
		config: '',
	},
	{
		title: 'Coseno Fi',
		names: ['Cos ϕ L1', 'Cos ϕ L2', 'Cos ϕ L3'],
		keys: ['CFi_0', 'CFi_1', 'CFi_2'],
		disable: false,
		config: {
			min: 0.75,
			max: 1,
			tickInterval: 0.035,
		},
	},
]
