export const controls = {
	NOJA: {
		RC_10: {
			basic: [
				{ id: 1, field: 'GRP', name: 'Grupo activo', type: 'circles' },
				{ id: 2, field: 'PROT', name: 'Protección', type: 'switch' },
				{ id: 3, field: 'AR', name: 'Recierre', type: 'switch' },
				{ id: 4, field: 'EF', name: 'Falla a tierra', type: 'switch' },
			],
			advance: [
				{ id: 5, field: 'CLP', type: 'switch', name: 'Carga en frío' },
				{ id: 6, field: 'SEF', type: 'switch', name: 'Falla a tierra sensible' },
				{ id: 7, field: 'customs', type: 'switch', name: 'Línea energizada ' },
				{ id: 8, field: 'customs', type: 'switch', name: 'Bloqueo Carga Viva' },
				{ id: 9, field: 'customs', type: 'switch', name: 'Cierre Bloqueado por Lógica' },
				{ id: 10, field: 'customs', type: 'switch', name: 'Modo Secuencia Corta' },
				{ id: 11, field: 'customs', type: 'switch', name: 'Sub tensión' },
				{ id: 12, field: 'DR', type: 'switch', name: 'Disparo rápidos' },
				{ id: 13, field: 'customs', type: 'switch', name: 'Sobre tensión' },
				{ id: 14, field: 'customs', type: 'switch', name: 'Sub frecuencia' },
				{ id: 15, field: 'customs', type: 'switch', name: 'Sobre frecuencia' },
				{ id: 16, field: 'customs', type: 'switch', name: 'Número máximo de disparos' },
				{ id: 17, field: 'customs', type: 'switch', name: 'Restauración Automática de Suministro' },
				{ id: 18, field: 'customs', type: 'switch', name: 'Armónicos' },
				{ id: 19, field: 'customs', type: 'switch', name: 'Secuencia de Fase Negativa' },
				{ id: 20, field: 'customs', type: 'switch', name: 'Caída de tensión Sag' },
				{ id: 21, field: 'customs', type: 'switch', name: 'Automatización Red Inteligente' },
				{ id: 22, field: 'customs', type: 'switch', name: 'Iniciar Auto-Sincronía' },
				{ id: 23, field: 'customs', type: 'switch', name: 'Cancelar Auto-Sincronía' },
				{ id: 24, field: 'customs', type: 'switch', name: 'Desplazamiento de neutro' },
				{ id: 25, field: 'customs', type: 'switch', name: 'Admitancia de neutro' },
				{ id: 26, field: 'customs', type: 'switch', name: 'Tasa de cambio de frecuencia' },
				{ id: 27, field: 'customs', type: 'switch', name: 'Cambio en vector de tensión ' },
				{ id: 28, field: 'customs', type: 'switch', name: 'Respaldo de interruptor' },
				{ id: 29, field: 'customs', type: 'switch', name: 'Sobre potencia direccional' },
				{ id: 30, field: 'customs', type: 'switch', name: 'Sub potencia direccional ' },
			],
		},
		RC_01: {
			basic: [
				{ id: 1, field: 'GRP', name: 'Grupo activo', type: 'circles' },
				{ id: 2, field: 'PROT', name: 'Protección', type: 'switch' },
				{ id: 3, field: 'AR', name: 'Recierre', type: 'switch' },
				{ id: 4, field: 'EF', name: 'Falla a tierra', type: 'switch' },
			],
			advance: [
				{ id: 6, field: 'SEF', type: 'switch', name: 'Falla a tierra sensible' },
				{ id: 5, field: 'CLP', type: 'switch', name: 'Carga en frío' },
				{ id: 7, field: 'customs', type: 'switch', name: 'Línea viva ' },
				{ id: 8, field: 'customs', type: 'switch', name: 'Sub tensión' },
				{ id: 8, field: 'customs', type: 'switch', name: 'Sub frecuencia' },
				{ id: 10, field: 'customs', type: 'switch', name: 'Restauración Automática de Suministro' },
			],
		},
	},
	COOPER: {
		f5: {
			basic: [
				{ id: 1, field: 'GRP', name: 'Grupo activo', type: 'circles' },
				{ id: 3, field: 'AR', name: 'Recierre', type: 'switch' },
				{ id: 4, field: 'EF', name: 'Falla a tierra', type: 'switch' },
				{ id: 2, field: 'customs', type: 'switch', name: 'Sobre Corriente' },
			],
			advance: [
				{ id: 6, field: 'SEF', type: 'switch', name: 'Falla a tierra sensible' },
				{ id: 5, field: 'CLP', type: 'switch', name: 'Carga en frío' },
				{ id: 7, field: 'customs', type: 'switch', name: 'Línea energizada ' },
				{ id: 8, field: 'customs', type: 'switch', name: 'Disparo por Tensión' },
				{ id: 9, field: 'customs', type: 'switch', name: 'Disparo por Frecuencia' },
				{ id: 10, field: 'customs', type: 'switch', name: 'Rearmado por tensión-frecuencia' },
				{ id: 12, field: 'DR', type: 'switch', name: 'Disparo rápidos' },
				{ id: 11, field: 'customs', type: 'switch', name: 'Reiniciar esquema de lazo' },
				{ id: 13, field: 'customs', type: 'switch', name: 'Deshabilitar esquema de lazo' },
				{ id: 14, field: 'customs', type: 'switch', name: 'Deshabilitar fuente 1' },
				{ id: 15, field: 'customs', type: 'switch', name: 'Deshabilitar fuente 2' },
			],
		},
	},
}
