export const boardStatus = [
	{ id: 1, field: 'alarm', name: 'Alarma' },
	{ id: 2, field: 'advr', name: 'Alerta' },
	{ id: 3, field: 'fail', name: 'Mal Función' },
	{ id: 4, field: 'blck', name: 'Bloqueo' },
	{ id: 5, field: 'malf', name: 'Mal Función' },
]

export const boardFields = [
	{ id: 1, field: 'name', name: 'Nombre' },
	{ id: 2, field: 'number', name: 'Número' },
	{ id: 3, field: 'serial', name: 'Nro de serie' },
	{ id: 4, field: 'brand', name: 'Fabricante' },
	{
		id: 5,
		field: 'ac',
		name: 'Alimentación',
		options: {
			0: <b className='text-green-500 text-xl'> Batería</b>,
			1: <b className='text-red-500 text-xl'> Red Electrica</b>,
		},
	},
	{
		id: 6,
		field: 'local',
		name: 'Modo',
		options: {
			0: <b className='text-black text-xl'> Remoto</b>,
			1: <b className='text-black bg-yellow-400 text-xl p-1 px-2 ml-1 rounded-md'>Local</b>,
		},
	},
]

export const boardControls = [
	{ id: 1, field: 'GRP', name: 'Grupo activo', type: 'circles' },
	{ id: 2, field: 'PROT', name: 'Protección', type: 'switch' },
	{ id: 3, field: 'AR', name: 'Recierre', type: 'switch' },
	{ id: 4, field: 'EF', name: 'Falla a tierra', type: 'switch' },
	{ id: 5, field: 'CLP', name: 'Carga en frío', type: 'switch' },
	{ id: 6, field: 'SEF', name: 'Falla a tierra sensible', type: 'switch' },
	{ id: 7, field: 'LL', name: 'Línea viva', type: 'switch' },
	{ id: 8, field: 'PT', name: 'Protección de tensión', type: 'switch' },
	{ id: 9, field: 'DF', name: 'Disparo por frecuencia', type: 'switch' },
	{ id: 10, field: 'DA', name: 'Disparo por armónicos', type: 'switch' },
	{ id: 11, field: 'PA', name: 'Protección por admitancia N', type: 'switch' },
	{ id: 12, field: 'DR', name: 'Disparo rápido', type: 'switch' },
]

export const boardMetrology = [
	{
		id: 1,
		name: 'Corrientes',
		children: [
			{ name: 'A', field: 'I_f_0', unit: 'A' },
			{ name: 'B', field: 'I_f_1', unit: 'A' },
			{ name: 'C', field: 'I_f_2', unit: 'A' },
			{ name: 'N', field: 'I_n', unit: 'A' },
		],
	},
	{
		id: 2,
		name: 'Tensión ABC',
		children: [
			{ name: 'A', field: 'V_f_ABC_0', unit: 'V' },
			{ name: 'AB', field: 'V_L_ABC_0', unit: 'V' },
			{ name: 'B', field: 'V_f_ABC_1', unit: 'V' },
			{ name: 'BC', field: 'V_L_ABC_1', unit: 'V' },
			{ name: 'C', field: 'V_f_ABC_2', unit: 'V' },
			{ name: 'CA', field: 'V_L_ABC_2', unit: 'V' },
		],
	},
	{
		id: 3,
		name: 'Tensión RST',
		children: [
			{ name: 'R', field: 'V_f_SRT_0', unit: 'V' },
			{ name: 'RS', field: 'V_L_SRT_0', unit: 'V' },
			{ name: 'S', field: 'V_f_SRT_1', unit: 'V' },
			{ name: 'ST', field: 'V_L_SRT_1', unit: 'V' },
			{ name: 'T', field: 'V_f_SRT_2', unit: 'V' },
			{ name: 'TR', field: 'V_L_SRT_2', unit: 'V' },
		],
	},
	{
		id: 4,
		name: 'Potencia',
		children: [
			{ name: 'Aparente (S)', field: 'W_0', unit: 'kW' },
			{ name: 'FP A', field: 'FP_f_0', unit: '' },
			{ name: 'Activa (P)', field: 'W_1', unit: 'kVA' },
			{ name: 'FP B', field: 'FP_f_1', unit: '' },
			{ name: 'Reactiva (Q)', field: 'W_2', unit: 'kVAr' },
			{ name: 'FP C', field: 'FP_f_2', unit: '' },
		],
	},
	{
		id: 5,
		name: 'UPS',
		children: [
			{ name: 'Tensión de batería', field: 'bat_0', unit: 'V' },
			{ name: 'Corriente de carga', field: 'bat_1', unit: 'V' },
			{ name: 'Carga efectiva', field: 'bat_2', unit: 'V' },
		],
	},
	{
		id: 6,
		name: 'Frecuencia',
		children: [{ name: 'Frecuencia', field: 'F_ABC', unit: 'Hz' }],
	},
]

export const recloser = [
	{
		id: 1,
		Nro_recloser: 0,
		Name: 'Marconi esq. Libertador',
		Nro_Serie: '01A1212030522',
		type_recloser: 1,
		brand: 'NOJA',
		version: 'RC_10',
		alarm_recloser: 0,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		status: 1,
		online: 0,
		Block: 0,
		Alert: 0,
		MalFunction: 0,
		Alarm: 0,
		GRP: 0,
		PROT: 0,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 2,
		Nro_recloser: 10,
		Name: 'Maunier',
		Nro_Serie: '0311720010029',
		type_recloser: 1,
		brand: 'NOJA',
		version: 'RC_10',
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 0,
		Alert: 0,
		MalFunction: 0,
		Alarm: 1,
		GRP: 2,
		PROT: 1,
		AR: 0,
		EF: 1,
		CLP: 0,
		SEF: 0,
		LL: 1,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 3,
		Nro_recloser: 102,
		Name: 'Adeco Agro',
		Nro_Serie: '18164214001',
		type_recloser: 1,
		brand: 'NOJA',
		version: 'RC_10',
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 0,
		Alert: 0,
		MalFunction: 0,
		Alarm: 0,
		GRP: 2,
		PROT: 1,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 4,
		Nro_recloser: 11,
		Name: 'Blangetti',
		Nro_Serie: '0311720010019',
		type_recloser: 1,
		brand: 'NOJA',
		version: 'RC_10',
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 1,
		Alert: 0,
		MalFunction: 0,
		Alarm: 1,
		GRP: 0,
		PROT: 0,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 5,
		Nro_recloser: 14,
		Name: 'Milessi',
		Nro_Serie: '03117191020611',
		type_recloser: 1,
		brand: 'NOJA',
		version: 'RC_10',
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 0,
		Alert: 1,
		MalFunction: 0,
		Alarm: 0,
		GRP: 0,
		PROT: 0,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 6,
		Nro_recloser: 6,
		Name: 'Dos Hermanos',
		Nro_Serie: '03117191020647',
		type_recloser: 1,
		brand: 'NOJA',
		version: 'RC_10',
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 0,
		Alert: 0,
		MalFunction: 1,
		Alarm: 0,
		GRP: 0,
		PROT: 0,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
]

export const dataCritics = [
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-26 21:38:17',
		event: 'Bloqueo',
		infoAdd: 'La = 558, LC = 675',
		statusAlert: 1,
	},
	{
		Nro_recloser: 10,
		Name: 'Marconi',
		dateAlert: '2024-06-26 20:08:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-20 11:30:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: '',
		Name: 'Alimentador 1',
		dateAlert: '2024-06-20 02:40:22',
		event: 'Apertura',
		infoAdd: 'VL1 = 0, VL" = 7896 V, VL· = 2v',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-18 23:50:17',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-26 21:38:17',
		event: 'Bloqueo',
		infoAdd: 'La = 558, LC = 675',
		statusAlert: 1,
	},
	{
		Nro_recloser: 10,
		Name: 'Marconi',
		dateAlert: '2024-06-26 20:08:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-20 11:30:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: '',
		Name: 'Alimentador 1',
		dateAlert: '2024-06-20 02:40:22',
		event: 'Apertura',
		infoAdd: 'VL1 = 0, VL" = 7896 V, VL· = 2v',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-18 23:50:17',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-26 21:38:17',
		event: 'Bloqueo',
		infoAdd: 'La = 558, LC = 675',
		statusAlert: 1,
	},
	{
		Nro_recloser: 10,
		Name: 'Marconi',
		dateAlert: '2024-06-26 20:08:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-20 11:30:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: '',
		Name: 'Alimentador 1',
		dateAlert: '2024-06-20 02:40:22',
		event: 'Apertura',
		infoAdd: 'VL1 = 0, VL" = 7896 V, VL· = 2v',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-18 23:50:17',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
]
export const rowManeuver = [
	{ action: 'AR_ON', user_name: 'RASPO JOAQUIN', date: '2024-01-10 06:14:00' },
	{ action: 'AR_OFF', user_name: 'DIAZ CORNEJO SANTIAGO JOSE', date: '2024-01-10 01:57:00' },
	{ action: 'AR_ON', user_name: 'RASPO JOAQUIN', date: '2023-12-29 06:29:00' },
	{ action: 'AR_OFF', user_name: 'RASPO JOAQUIN', date: '2023-12-28 23:24:00' },
	{ action: 'AR_ON', user_name: 'DIAZ CORNEJO SANTIAGO JOSE', date: '2023-12-24 08:49:00' },
	{ action: 'AR_OFF', user_name: 'DIAZ CORNEJO SANTIAGO JOSE', date: '2023-12-24 08:10:00' },
]
