export const ColumnsTable = [
	{
		id: 'datePeriod',
		accessorKey: 'datePeriod',
		filterVariant: 'date-range',
		Cell: ({ cell }) => `${cell.getValue().toLocaleDateString()} ${cell.getValue().toLocaleTimeString()}`, // convert back to string for display
		header: 'Fecha el Periodo',
	},
	{
		header: 'Canal 1 (V)',
		accessorKey: 'Canal1',
		muiFilterTextFieldProps: { placeholder: 'Canal 1' },
		size: 140,
		enableColumnFilter: false,
		enableSorting: false,
	},
	{
		header: 'Canal 2 (V)',
		accessorKey: 'Canal2',
		muiFilterTextFieldProps: { placeholder: 'Canal 2' },
		size: 140,
		enableColumnFilter: false,
		enableSorting: false,
	},
	{
		header: 'Canal 3 (V)',
		accessorKey: 'Canal3',
		muiFilterTextFieldProps: { placeholder: 'Canal 3' },
		size: 140,
		enableColumnFilter: false,
		enableSorting: false,
	},
	{
		header: 'Canal 4',
		accessorKey: 'Canal4',
		muiFilterTextFieldProps: { placeholder: 'Canal 4' },
		size: 140,
		enableColumnFilter: false,
		enableSorting: false,
	},
	{
		header: 'Canal 5 (kW)',
		accessorKey: 'Canal5',
		muiFilterTextFieldProps: { placeholder: 'Canal 5' },
		size: 140,
		enableColumnFilter: false,
		enableSorting: false,
	},
	{
		header: 'Canal 6 (kW)',
		accessorKey: 'Canal6',
		muiFilterTextFieldProps: { placeholder: 'Canal 6' },
		size: 140,
		enableColumnFilter: false,
		enableSorting: false,
	},
	{
		header: 'Canal 7 (kW)',
		accessorKey: 'Canal7',
		muiFilterTextFieldProps: { placeholder: 'Canal 7' },
		size: 140,
		enableColumnFilter: false,
		enableSorting: false,
	},
	{
		header: 'Canal 8',
		accessorKey: 'Canal8',
		muiFilterTextFieldProps: { placeholder: 'Canal 8' },
		size: 140,
		enableColumnFilter: false,
		enableSorting: false,
	},
	{
		header: 'Eventos',
		accessorKey: 'Event',
		muiFilterTextFieldProps: { placeholder: 'Eventos' },
		enableColumnFilter: false,
		enableSorting: false,
	},
]
