export const menus = [
	{
		id: '1',
		name: 'Acueducto',
		action: '',
		icon: '',
		level: '0',
		group_menu: '1',
		sub_menu: null,
		status: '1',
	},
	{
		id: '2',
		name: 'Administración',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
	},
	{
		id: '40',
		name: 'Inmuebles - Contribuyentes',
		action: 'acueduct_texpayers()',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
	},
	{
		id: '51',
		name: 'Facturación',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
	},
	{
		id: '64',
		name: 'Tesoreria y Cajas',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
	},
	{
		id: '74',
		name: 'Gestión de Deuda',
		action: '',
		icon: '',
		level: '1',
		group_menu: '1',
		sub_menu: '1',
		status: '1',
	},
	{
		id: '45',
		name: 'Conceptos',
		action: 'concepts_aqueduct()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
	},
	{
		id: '46',
		name: 'Tipos de Comprobantes',
		action: 'acueduct_Type_voucher_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
	},
	{
		id: '47',
		name: 'Referencias',
		action: 'aqueduct_references()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
	},
	{
		id: '48',
		name: 'Parámetros',
		action: 'aqueduct_parameter_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
	},
	{
		id: '49',
		name: 'Tipos Planes de Pago',
		action: 'payment_plans_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
	},
	{
		id: '50',
		name: 'Importar Calles',
		action: 'acueduct_importTXT()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
	},
	{
		id: '52',
		name: 'Facturación manual',
		action: 'viewInvoicesIndividual()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
	},
	{
		id: '54',
		name: 'Cambio d/Precios Masivo',
		action: 'aqueduct_update_dues()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
	},
	{
		id: '55',
		name: 'Prefacturación',
		action: 'pre_invoicing()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
	},
	{
		id: '57',
		name: 'Facturación Masiva',
		action: 'invoicing()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
	},
	{
		id: '58',
		name: 'Control Facturación',
		action: 'filter_invoice()',
		icon: 'fa fa-file',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
	},
	{
		id: '59',
		name: 'Informes',
		action: '',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
	},
	{
		id: '65',
		name: 'Consulta de Cajas',
		action: 'aqueduct_list_box()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '66',
		name: 'Cobranza Local',
		action: 'box_collection()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '67',
		name: 'Operaciones de Caja',
		action: 'operation_box()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '69',
		name: 'Planilla s/Recibo',
		action: 'recipes_list()',
		icon: 'fas fa-receipt',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '70',
		name: 'Importar Cobranza',
		action: 'import_pay_ext()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '71',
		name: 'Consulta Cobranzas Ext.',
		action: 'collection_consultation()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '72',
		name: 'Cheques Recibidos',
		action: 'aqueduct_check_received()',
		icon: 'fas fa-money-check',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '73',
		name: 'Tarjetas Recibidas',
		action: 'aqueduct_cards_received()',
		icon: 'fas fa-credit-card',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '75',
		name: 'Emitir Plan de Pago',
		action: 'payment_plans()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
	},
	{
		id: '76',
		name: 'Consulta Plan de Pago',
		action: 'pyment_consult_list()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
	},
	{
		id: '77',
		name: 'Desbloquear Cedulones',
		action: 'aqueduct_blocked()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '74',
		status: '1',
	},
	{
		id: '82',
		name: 'Importar Inmuebles',
		action: 'import_txt_muni()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
	},
	{
		id: '87',
		name: 'Totales Cobrados',
		action: 'acueduct_total_cobros()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '64',
		status: '1',
	},
	{
		id: '91',
		name: 'Generar Cuotas',
		action: 'aqueduct_importFee()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
	},
	{
		id: '92',
		name: 'Usuarios Vinculados',
		action: 'users_accounts_aqueduct()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '2',
		status: '1',
	},
	{
		id: '93',
		name: 'Exportar Cedulones',
		action: 'aqueduct_exportPayments()',
		icon: '',
		level: '2',
		group_menu: '1',
		sub_menu: '51',
		status: '1',
	},
	{
		id: '60',
		name: 'Cuotas No Facturadas',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
	},
	{
		id: '61',
		name: 'Notas de Créditos',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
	},
	{
		id: '62',
		name: 'Cuentas No Facturar',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
	},
	{
		id: '63',
		name: 'Comp. Bloqueados',
		action: '',
		icon: '',
		level: '3',
		group_menu: '1',
		sub_menu: '59',
		status: '1',
	},
	{
		id: '80',
		name: 'Desarrollo',
		action: '',
		icon: 'fa fa-file',
		level: '0',
		group_menu: '2',
		sub_menu: null,
		status: '1',
	},
	{
		id: '81',
		name: 'Migración Acueducto',
		action: 'prueba_jose2()',
		icon: '',
		level: '1',
		group_menu: '2',
		sub_menu: '80',
		status: '1',
	},
	{
		id: '83',
		name: 'Coopate',
		action: '',
		icon: 'fas fa-dumpster',
		level: '0',
		group_menu: '3',
		sub_menu: null,
		status: '1',
	},
	{
		id: '84',
		name: 'Beneficios CoopMorteros',
		action: 'grafico_canjes_coop()',
		icon: '',
		level: '1',
		group_menu: '3',
		sub_menu: '83',
		status: '1',
	},
	{
		id: '85',
		name: 'Graficos Externos',
		action: 'grafico_canjes_x_socio()',
		icon: '',
		level: '1',
		group_menu: '3',
		sub_menu: '83',
		status: '1',
	},
]
