export const boardStatus = [
	{ id: 1, field: 'Alarm', name: 'Alarma' },
	{ id: 2, field: 'Alert', name: 'Alerta' },
	{ id: 3, field: 'MalFunction', name: 'Mal Función' },
	{ id: 4, field: 'Block', name: 'Bloqueo' },
]

export const boardFields = [
	{ id: 1, field: 'Name', name: 'Nombre' },
	{ id: 2, field: 'Nro_recloser', name: 'Número' },
	{ id: 3, field: 'Nro_Serie', name: 'Nro de serie' },
	{ id: 4, field: 'Alim', name: 'Alimentación' },
	{ id: 5, field: 'Mod', name: 'MODO' },
]

export const boardControls = [
	{ id: 1, field: 'GRP', name: 'Grupo activo', type: 'circles' },
	{ id: 2, field: 'PROT', name: 'Protección', type: 'switch' },
	{ id: 3, field: 'AR', name: 'Recierre', type: 'switch' },
	{ id: 4, field: 'EF', name: 'Falla a tierra', type: 'switch' },
	{ id: 5, field: 'CLP', name: 'Carga en frío', type: 'switch' },
	{ id: 6, field: 'SEF', name: 'Falla a tierra sensible', type: 'switch' },
	{ id: 7, field: 'LL', name: 'Línea viva', type: 'switch' },
	{ id: 8, field: 'PT', name: 'Protección de tensión', type: 'switch' },
	{ id: 9, field: 'DF', name: 'Disparo por frecuencia', type: 'switch' },
	{ id: 10, field: 'DA', name: 'Disparo por armónicos', type: 'switch' },
	{ id: 11, field: 'PA', name: 'Protección por admitancia N', type: 'switch' },
	{ id: 12, field: 'DR', name: 'Disparo rápido', type: 'switch' },
]

export const boardMetrology = [
	{
		id: 1,
		name: 'Corrientes',
		children: [
			{ name: 'A', value: '15 A' },
			{ name: 'B', value: '14 A' },
			{ name: 'C', value: '16 A' },
			{ name: 'N', value: '0 A' },
		],
	},
	{
		id: 2,
		name: 'Tensión ABC',
		children: [
			{ name: 'A', value: '7900 V' },
			{ name: 'AB', value: '13500 V' },
			{ name: 'B', value: '7700 V' },
			{ name: 'BC', value: '13500 V' },
			{ name: 'C', value: '7900 V' },
			{ name: 'CA', value: '13700 V' },
		],
	},
	{
		id: 3,
		name: 'Tensión SRT',
		children: [
			{ name: 'R', value: '7900 V' },
			{ name: 'RS', value: '13500 V' },
			{ name: 'S', value: '7700 V' },
			{ name: 'ST', value: '13500 V' },
			{ name: 'T', value: '7900 V' },
			{ name: 'TR', value: '13700 V' },
		],
	},
	{
		id: 4,
		name: 'Potencia',
		children: [
			{ name: 'S', value: '348 kVA' },
			{ name: 'FP A', value: '0.91' },
			{ name: 'P', value: '314 kW' },
			{ name: 'FP B', value: '0.91' },
			{ name: 'Q', value: '149 kVAr' },
			{ name: 'FP C', value: '0.90' },
		],
	},
	{
		id: 5,
		name: 'UPS',
		children: [
			{ name: 'Tensión de batería', value: '13.42 V' },
			{ name: 'Corriente de carga', value: '0 A' },
			{ name: 'Carga efectiva', value: '100 %' },
		],
	},
]

export const recloser = [
	{
		id: 1,
		Nro_recloser: 0,
		Name: 'Marconi esq. Libertador',
		Nro_Serie: '01A1212030522',
		type_recloser: 1,
		alarm_recloser: 0,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		status: 1,
		online: 0,
		Block: 0,
		Alert: 0,
		MalFunction: 0,
		Alarm: 0,
		GRP: 0,
		PROT: 0,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 2,
		Nro_recloser: 10,
		Name: 'Maunier',
		Nro_Serie: '0311720010029',
		type_recloser: 1,
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 0,
		Alert: 0,
		MalFunction: 0,
		Alarm: 1,
		GRP: 2,
		PROT: 1,
		AR: 0,
		EF: 1,
		CLP: 0,
		SEF: 0,
		LL: 1,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 3,
		Nro_recloser: 102,
		Name: 'Adeco Agro',
		Nro_Serie: '18164214001',
		type_recloser: 1,
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 0,
		Alert: 0,
		MalFunction: 0,
		Alarm: 0,
		GRP: 2,
		PROT: 1,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 4,
		Nro_recloser: 11,
		Name: 'Blangetti',
		Nro_Serie: '0311720010019',
		type_recloser: 1,
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 1,
		Alert: 0,
		MalFunction: 0,
		Alarm: 1,
		GRP: 0,
		PROT: 0,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 5,
		Nro_recloser: 14,
		Name: 'Milessi',
		Nro_Serie: '03117191020611',
		type_recloser: 1,
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 0,
		Alert: 1,
		MalFunction: 0,
		Alarm: 0,
		GRP: 0,
		PROT: 0,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
	{
		id: 6,
		Nro_recloser: 6,
		Name: 'Dos Hermanos',
		Nro_Serie: '03117191020647',
		type_recloser: 1,
		status: 0,
		online: 1,
		alarm_recloser: 1,
		Mod: 'REMOTO',
		Alim: 'Red Electrica',
		Block: 0,
		Alert: 0,
		MalFunction: 1,
		Alarm: 0,
		GRP: 0,
		PROT: 0,
		AR: 0,
		EF: 0,
		CLP: 0,
		SEF: 0,
		LL: 0,
		PT: 0,
		DF: 0,
		DA: 0,
		PA: 0,
		DR: 0,
	},
]

export const dataCritics = [
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-26 21:38:17',
		event: 'Bloqueo',
		infoAdd: 'La = 558, LC = 675',
		statusAlert: 1,
	},
	{
		Nro_recloser: 10,
		Name: 'Marconi',
		dateAlert: '2024-06-26 20:08:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-20 11:30:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: '',
		Name: 'Alimentador 1',
		dateAlert: '2024-06-20 02:40:22',
		event: 'Apertura',
		infoAdd: 'VL1 = 0, VL" = 7896 V, VL· = 2v',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-18 23:50:17',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-26 21:38:17',
		event: 'Bloqueo',
		infoAdd: 'La = 558, LC = 675',
		statusAlert: 1,
	},
	{
		Nro_recloser: 10,
		Name: 'Marconi',
		dateAlert: '2024-06-26 20:08:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-20 11:30:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: '',
		Name: 'Alimentador 1',
		dateAlert: '2024-06-20 02:40:22',
		event: 'Apertura',
		infoAdd: 'VL1 = 0, VL" = 7896 V, VL· = 2v',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-18 23:50:17',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-26 21:38:17',
		event: 'Bloqueo',
		infoAdd: 'La = 558, LC = 675',
		statusAlert: 1,
	},
	{
		Nro_recloser: 10,
		Name: 'Marconi',
		dateAlert: '2024-06-26 20:08:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-20 11:30:07',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
	{
		Nro_recloser: '',
		Name: 'Alimentador 1',
		dateAlert: '2024-06-20 02:40:22',
		event: 'Apertura',
		infoAdd: 'VL1 = 0, VL" = 7896 V, VL· = 2v',
		statusAlert: 1,
	},
	{
		Nro_recloser: 0,
		Name: 'Maunier',
		dateAlert: '2024-06-18 23:50:17',
		event: 'Bloqueo',
		infoAdd: '',
		statusAlert: 0,
	},
]
export const rowManeuver = [
	{ action: 'AR_ON', user_name: 'RASPO JOAQUIN', date: '2024-01-10 06:14:00' },
	{ action: 'AR_OFF', user_name: 'DIAZ CORNEJO SANTIAGO JOSE', date: '2024-01-10 01:57:00' },
	{ action: 'AR_ON', user_name: 'RASPO JOAQUIN', date: '2023-12-29 06:29:00' },
	{ action: 'AR_OFF', user_name: 'RASPO JOAQUIN', date: '2023-12-28 23:24:00' },
	{ action: 'AR_ON', user_name: 'DIAZ CORNEJO SANTIAGO JOSE', date: '2023-12-24 08:49:00' },
	{ action: 'AR_OFF', user_name: 'DIAZ CORNEJO SANTIAGO JOSE', date: '2023-12-24 08:10:00' },
]
